# Generated by Django 3.2.9 on 2021-12-23 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='liked_by',
        ),
    ]
